### PR TITLE
my first pull request

### PR DESCRIPTION
**Pull request by Feliverse**
The index.html and style.css are working

### CODE REVIEW

**Comment by Feliverse** [comment]
I need help with the setup linters, please

**Review by Felix45 — CHANGES_REQUESTED** [review]
Hi @Feliverse  

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights :heavy_check_mark: 
- [ ] Application is working as expected
- [ ] Correct use of GitHub flow
- [ ] Good and descriptive commit messages


almost-there

## Required Changes ♻️
- [x] Your project  readme would be much better if you included the information from the [Microverse readme template](https://github.com/microverseinc/readme-template/blob/master/README.md) provided by Microverse, please update your readme file using this template
- [x] Please consider setting up `Webhint` and `Stlyle lint` linters on your project. Linter checking helps you write clean code, you can get more instructions on setting up HTML & CSS linters on this link [Click here >>](https://github.com/microverseinc/linters-config/tree/master/html-css)
- [x]  Please consider adding a more descriptive summary of all the changes that were introduced in this pull request. The current summary does not describe all the changes that were introduced in this pull request.
Desc Screenshot from 2022-10-27 03-20-25

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Felix45** [comment]
> I need help with the setup linters, please

Hi @Feliverse , I've included a link with instructions on how to set up [HTML & CSS linters](https://github.com/microverseinc/linters-config/tree/master/html-css) on your project in the review I've posted above. Please reach out to me on `slack` @Felix Ouma in case you face any difficulty in setting up the linters.

**Comment by Feliverse** [comment]
Hi @Felix45, Thank you for your feedback, I resolve all the observations, please review them

**Review by pinkmoon25 — CHANGES_REQUESTED** [review]
Hi @Feliverse , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.



 ## Highlights
github flow is correct :heavy_check_mark: 
Added index.html and css :heavy_check_mark: 

 ## Required Changes ♻️
_Check the comments under the review._

- [x] As mentioned by the previous reviewer please add .stylelint.json and .hintrc file to your root folder here is the [link](https://github.com/microverseinc/linters-config/tree/master/html-css) you will find the .stylelint.json and .hintrc files please copy them and add them to your root folder. 

- [x] After copying the files, run the installations command that you will find inside .github/workflows/linter.yml it will look like :point_down: 
```
 run: |
          npm install --save-dev hint@7.x
```
:point_up:  this will install the webhint and generate package.json and node modules for you

this one will install .stylelint :point_down: 
```
run: |
          npm install --save-dev stylelint@13.x stylelint-scss@3.x stylelint-config-standard@21.x stylelint-csstree-validator@1.x
```

- [x] Then please add the newly generated `node_modules` folder in th `.gitignore` file 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Feliverse** [comment]
Hi @PinkMoon25,
I find the error, in my root, the carpet said workflow, I change it to workflows, and now the linter works perfectly, please a last review

**Review by Debas-31 — APPROVED** [review]
> ## Hi @Feliverse 
# Status: Approved :green_circle: 

Great work on making the changes requested by a previous reviewer. Your project is complete !  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


## Highlights
- GitHub flow :heavy_check_mark: 
- Project working :heavy_check_mark: 

## Optional suggestions

 [ OPTIONAL] - kindly add a title and descriptive summary to the PR.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
